name: theme_extensions_annotation
description: annotations for theme_extensions_generator
version: 1.1.2
repository: https://github.com/MiiMan/theme_extensions_generator

environment:
  sdk: '>=3.4.1 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
