name: theme_extensions_generator
description: Code generation for theme extensions
version: 1.0.0
repository: https://github.com/MiiMan/theme_extensions_generator

environment:
  sdk: ">=2.17.0 <3.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  build: any
  analyzer: any
  source_gen: any
  theme_extensions_annotation:
    git:
      url: https://github.com/MiiMan/theme_extensions_generator.git
      path: theme_extensions_annotation

dev_dependencies:
  build_test: any
  build_runner: any
  lints: ^2.0.0
  test: ^1.21.0
